### ISSUE TITLE
Question on Masking (i.e. attention bias) Upon Cross-Attention

### ISSUE THREAD

**Issue by BorisPolonsky** [liu-nlper/dialogue-utterance-rewriter#4]
I replicated the result and read through your code. In your implementation, each of the subblocks in decoder concatenates outputs from two cross-attention ops with different masking logic, namely *query bias* and *content bias*. I would like to know what part of encoder input will be masked out respectively given these two biases. 

I read the code in `models_utils.py`, it appears that there are three kinds of biases. 
The commonly used bias for masking out paddings in encoder inputs (i.e. `attention_bias_query`):
https://github.com/liu-nlper/dialogue-utterance-rewriter/blob/3e0289d12e9bbfe1fb350f2b7377efd732dc2896/transformer/model/model_utils.py#L118

The bias for masking paddings plus some additional tokens, given `mask`:
https://github.com/liu-nlper/dialogue-utterance-rewriter/blob/3e0289d12e9bbfe1fb350f2b7377efd732dc2896/transformer/model/model_utils.py#L132

(It seems that the corresponding area of `mask` and `padding` are mutually exclusive here given that you apply `masks + padding` statement for `OR` logic). 

And a query mask, which appears to apply `NOT` logic upon `mask`

https://github.com/liu-nlper/dialogue-utterance-rewriter/blob/3e0289d12e9bbfe1fb350f2b7377efd732dc2896/transformer/model/model_utils.py#L126

I would like to know which part of the encoder inputs will be masked given `attention_bias_query` and `attention_bias_content`, respectively. And the intuition behind it. A specific example explaining the logic for creating the `mask` will definitely help.

Thank you & Good work replicating the original paper.

PS:
I found a typo here (flaot -> float):
https://github.com/liu-nlper/dialogue-utterance-rewriter/blob/3e0289d12e9bbfe1fb350f2b7377efd732dc2896/transformer/model/transformer.py#L498

**Comment by LLLLLLoki** [comment]
i find this problem, attnetion_bias_content looks like it's all minus infinity,that right??

**Comment by BorisPolonsky** [comment]
> i find this problem, attnetion_bias_content looks like it's all minus infinity,that right??

I looked through the code, the code is correct, the input of transformer is organized as `inputs_ids = [CLS_ID] + [EOS_ID] + query_ids + [SEP_ID] + content_ids`
where `query_ids` corresponds to the current input, while `content_ids` corresponds to history.

**Comment by LLLLLLoki** [comment]
Thank you for your answer
